core/urls.py
#from core.views import LocaisList, IndexTemplateView, LocalDetailView, RegCreateView, Pt1CreateView
from core.views import IndexTemplateView
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [


    path('', IndexTemplateView.as_view(), name="index"),
   #  path('pt1/', views.pt1_new, name='pt1'),



 ]
 
    # path('pt1/', Pt1CreateView.as_view(), name="pt1"),
    # path('post/<int:pk>/', views.post_detail, name='post_detail'),
    # path('post/new/', views.post_new, name='post_new'),
    # path('pt2/', situacoes, name="pt2"),  
    # path("sit_m/", sit_met, name="sit_m"),
    # path("si_m/", si_m, name="si_m"),
    # path("mi_col/", mi_col, name="mi_col"),
    # GET/POST /funcionario/{pk}
    #path('pt2/<pk>', Pt2UpdateView.as_view(), name="parte2"),
    # GET /localidades
    #path('locais/', LocaisList.as_view(), name="lista_locais"),
    # GET/POST /local_detail/{pk}
    #path('local_detail/<pk>', LocalDetailView.as_view(), name="detail_local"),
    # GET /aditivo/cadastrar
    #path('add_reg/', RegCreateView.as_view(), name="add_reg"),
    # GET/POST /pasta/{pk}
    #path('pasta/<pk>', PastaDetailView.as_view(), name="detail_pasta"),
    # GET /funcionarios
    # path('<int:pasta_id>/', views.getPastas, name='getPastas'),
    # GET /funcionarios
    #path('cpa/', PastaCreateView.as_view(), name="cpa"),
    # GET/POST /funcionario/{pk}
    #path('aditivo/<pk>', AditivoUpdateView.as_view(), name="atualiza_aditivo"),
    # GET/POST /funcionarios/excluir/{pk}
    #path('aditivo/excluir/<pk>', AditivoDeleteView.as_view(), name="deleta_aditivo"),

projd/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

from django.urls.conf import include

urlpatterns = [
    path('', include('core.urls', namespace='core')),



    path('admin/', admin.site.urls),

    ]

#Add Django Debug Toolbar
# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

#Add Django site authentication urls (for login, logout, password management)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

core/models.py
from django.db import models

# Create your models here.
class Reporter(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField()

    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name)

class Article(models.Model):
    headline = models.CharField(max_length=100)
    pub_date = models.DateField()
    reporter = models.ForeignKey(Reporter, on_delete=models.CASCADE)

    def __str__(self):
        return self.headline

    class Meta:
        ordering = ['headline']

core/views.py
from django.shortcuts import render, redirect
from django.views.generic import View,TemplateView, CreateView, UpdateView, DetailView
from django.urls import reverse_lazy
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin #para Classes Based Views
from django.contrib.auth.decorators import login_required #para Functions Based Views

from django.db.models import Sum, Avg, F
from django.db.models.functions import Coalesce


import json
import datetime

from core.models import Reporter, Article

# Create your views here.
class IndexTemplateView(TemplateView):
    template_name = "core/index.html"

core/templates/core/_layouts/base.html
<!doctype html>
{% load static %}

<html lang="PT-BR" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Fernando Antonio Pedreira Perazzo">
    <meta name="generator" content="Jekyll v4.0.1">
    <title>Orçamentos</title>

       <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" href="{%static 'core/css/bootstrap.min.css' %}">
  </head>

  <!-- Fixed navbar -->
  
  <body class="d-flex flex-column h-100">
    <header>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color: #1b7a2d;">
      <div class="container">
      <a class="navbar-brand" href="{% url 'core:index' %}">
      <img src="{%static 'core/img/favicon.ico' %}" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">rçamentos
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'core:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Meus Orçamentos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Novo</a>
            </li>

        </div>
      </div>
    </nav>
    </header>

<!-- Begin page content -->
  <main role="main" class="flex-shrink-0">
    <script
      src="https://code.jquery.com/jquery-3.4.1.min.js"
      integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
      crossorigin="anonymous"
    ></script>
  {% block conteudo %}{% endblock %}
  </main>

  <footer class="footer mt-auto py-3">
    <div class="container" style="text-align: center;">
      <span class="text-muted">
        {% if user.is_authenticated %}Logado como: {{ user.get_username }} 
        <a href="{% url 'logout'%}?next={{request.path}}"> Sair</a>
        {% else %}
        <a href="{% url 'login'%}?next={{request.path}}">Fazer Login</a>
        {% endif %}
          - Em caso de dúvidas: fernando_perazzo@yahoo.com.br
    </span>
    </div>
  </footer>

  <script src="{% static 'core/js/bootstrap.bundle.min.js' %}"></script>
    {% block scripts %}{% endblock scripts%}

  </body>
</html>

core/templates/core/index.html
<!-- Estendemos do template base -->
{% extends "core/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Página Inicial{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}

<div class="container mt-5">
<h2><a href="{% url 'core:index' %}">Gerar Orçamento</a></h2>
</br>
	<p class="mb-3">{% lorem %}</p>
	<p class="mb-3">{% lorem %}</p>
	<p class="mb-3">{% lorem %}</p>
	<p class="mb-3">{% lorem %}</p>

 </div>
{% endblock %}